### ISSUE TITLE
اقتراح

### ISSUE THREAD

**Issue by ahmedbatook** [iMokhles/DzSnap-issues#1]
اتمنى اداة Dzsnap تدعم سناب مكرر وما اعتقد شيء صعب  اتمنى لكم كل التوفيق وشكرا لكم على ابداعكم❤️

**Comment by iMokhles** [comment]
الاداه فعليا تدعم نسختين من السناب المكرر بالمعرفات التاليه
com.toyopagroup.picaboo2
com.toyopagroup.picaboo3

**Comment by ahmedbatook** [comment]
انا لا اقصد ذلك اخ مخلص انا اقصد تدعم نسخه سناب اخرى يعني تطبيق سناب اخر
اسف على عدم التعمق في الاقتراح 👍🏻

في ثلاثاء، ١٦ أبريل، ٢٠١٩ في ٥:٣٤ م، كتب Mokhlas Hussein <
notifications@github.com>:
